
MODULE INITIALIZATION          msecs      invoked at
pre-Module.Startup               172    14:06:01.889
NodeBase.NbModule...                    14:06:02.061
...initialized                   105
NodeTools.NtModule...                   14:06:02.176
...initialized                    52
CodeTools.CtModule...                   14:06:02.236
...initialized                    30
NetworkBase.NwModule...                 14:06:02.275

    NET500 12-May-2020 14:06:02.291 on Reigi {1}
...initialized                    81
SessionBase.SbModule...                 14:06:02.364
...initialized                    97
ControlNode.CnModule...                 14:06:02.470
...initialized                     7
SessionTools.StModule...                14:06:02.485
...initialized                    22
MediaBase.MbModule...                   14:06:02.520
...initialized                    20
CallBase.CbModule...                    14:06:02.554
...initialized                    27
PotsBase.PbModule...                    14:06:02.592
...initialized                    27
OperationsNode.OnModule...              14:06:02.629
...initialized                    11
RoutingNode.RnModule...                 14:06:02.652
...initialized                    10
ServiceNode.SnModule...                 14:06:02.674
...initialized                    56
AccessNode.AnModule...                  14:06:02.741
...initialized                    19
                               -----
total initialization time        882

    NODE500 12-May-2020 14:06:02.783 on Reigi {2}
nb>read test.trap.all
nb>/ MAKE RECOVERY TEST THREAD CRITICAL
nb>read test.trap.setup
nb>quit all
  Nothing to quit.
nb>nt
nt>swflags set &flag.reenterthread on
  OK.
nt>read test.tools.setup
nt>stop
  OK.
nt>clear buffer
  OK.
nt>clear selections
  OK.
nt>clear tools
  OK.
nt>set tools f on
  f: OK.
  OK.
nt>/ set scope counts  / enables full function trace if commented out
nt>include all on
  OK.
nt>read test.trap.tools.setup
nt>exclude faction &faction.audit
  OK.
nt>exclude faction &faction.bkgd
  OK.
nt>exclude faction &faction.oper
  OK.
nt>exclude faction &faction.mtce
  OK.
nt>exclude faction &faction.payload
  OK.
nt>include faction &faction.system
  OK.
nt>testcase prolog test.trap.prolog
  OK.
nt>testcase epilog test.trap.epilog
  OK.
nt>recover create
  OK.
nt>swflags set &flag.disablerootthread on
  OK.
nt>testcase begin recover.Return
symbols set testcase.name recover.Return
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.01
nt>/ RECOVER return
nt>recover return
nt>
    THR901 12-May-2020 14:06:10.430 on Reigi {3}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00006da0)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Return completed.
nt>testcase begin recover.SwErr
symbols set testcase.name recover.SwErr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.02
nt>/ RECOVER swerr
nt>recover swerr
nt>
    THR902 12-May-2020 14:06:13.076 on Reigi {4}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004098): trap number 1
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 205[65]
      NodeTools.RecoveryThread.DoSwerr @ ntincrement.cpp + 4098[22]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4184[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SwErr completed.
nt>testcase begin recover.BadPtrExit
symbols set testcase.name recover.BadPtrExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.24
nt>/ RECOVER dereference bad pointer and exit thread
nt>swflags set &flag.reenterthread off
nt>delay 1
nt>recover badptr
nt>
    THR902 12-May-2020 14:06:15.942 on Reigi {5}
    in NodeTools.RecoveryThread (tid=15, nid=0x00004098): trap number 2
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4153[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR901 12-May-2020 14:06:15.943 on Reigi {6}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00004098)
    signal=11 (SIGSEGV: Invalid Memory Reference)
delay 1
nt>swflags set &flag.reenterthread on
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:18.059 on Reigi {7}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:18.157 on Reigi {8}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=99 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtrExit completed.
nt>testcase begin recover.BadPtr
symbols set testcase.name recover.BadPtr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.03
nt>/ RECOVER dereference bad pointer
nt>recover badptr
nt>
    THR902 12-May-2020 14:06:19.273 on Reigi {9}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006260): trap number 3
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4153[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtr completed.
nt>testcase begin recover.DivZero
symbols set testcase.name recover.DivZero
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.04
nt>/ RECOVER divide by zero
nt>recover divide
nt>
    THR902 12-May-2020 14:06:21.111 on Reigi {10}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006260): trap number 4
    type=Signal
    signal : 8 (SIGFPE: Erroneous Arithmetic Operation)
    errval : 0xc0000094
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4156[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:22.202 on Reigi {11}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:22.248 on Reigi {12}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=46 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DivZero completed.
nt>testcase begin recover.SIGINT
symbols set testcase.name recover.SIGINT
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.05
nt>/ RECOVER raise interrupt
nt>recover raise SIGINT
nt>
    THR902 12-May-2020 14:06:23.019 on Reigi {13}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006260): trap number 5
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 3233[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 4087[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4177[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGINT completed.
nt>testcase begin recover.SIGILL
symbols set testcase.name recover.SIGILL
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.06
nt>/ RECOVER raise illegal instruction
nt>recover raise SIGILL
nt>
    THR902 12-May-2020 14:06:25.076 on Reigi {14}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006260): trap number 6
    type=Signal
    signal : 4 (SIGILL: Illegal Instruction)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 3233[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 4087[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4177[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:26.178 on Reigi {15}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:26.204 on Reigi {16}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=46 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGILL completed.
nt>testcase begin recover.SIGTERM
symbols set testcase.name recover.SIGTERM
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.07
nt>/ RECOVER raise termination from kill
nt>recover raise SIGTERM
nt>
    THR902 12-May-2020 14:06:26.919 on Reigi {17}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006260): trap number 7
    type=Signal
    signal : 15 (SIGTERM: Termination Request)
    errval : 0x0
    TRAP LIMIT EXCEEDED.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 3233[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 4087[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4177[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR906 12-May-2020 14:06:26.919 on Reigi {18}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00006260)
    signal=15 (SIGTERM: Termination Request)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGTERM completed.
nt>testcase begin recover.SIGBREAK
symbols set testcase.name recover.SIGBREAK
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.08
nt>/ RECOVER raise ctrl-break
nt>recover raise SIGBREAK
nt>
    THR902 12-May-2020 14:06:28.871 on Reigi {19}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003d34): trap number 8
    type=Signal
    signal : 21 (SIGBREAK: Ctrl-Break)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 3233[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 4087[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4177[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGBREAK completed.
nt>testcase begin recover.abort
symbols set testcase.name recover.abort
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.09
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER abort
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover abort
nt>
    THR902 12-May-2020 14:06:35.392 on Reigi {20}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003d34): trap number 9
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 3233[11]
      raise @ <unknown file> (err=487)
      abort @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoAbort @ ntincrement.cpp + 4053[8]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4144[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:37.532 on Reigi {21}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:37.808 on Reigi {22}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=297 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.abort completed.
nt>testcase begin recover.terminate
symbols set testcase.name recover.terminate
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.10
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER terminate
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover terminate
nt>
    THR902 12-May-2020 14:06:44.782 on Reigi {23}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003d34): trap number 10
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 3233[11]
      raise @ <unknown file> (err=487)
      abort @ <unknown file> (err=487)
      terminate @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoTerminate @ ntincrement.cpp + 4109[8]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4187[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:46.904 on Reigi {24}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:47.119 on Reigi {25}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=216 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.terminate completed.
nt>testcase begin recover.KillLocal
symbols set testcase.name recover.KillLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.11
nt>/ RECOVER kill this
nt>recover trap t SIGPURGE
nt>
    THR902 12-May-2020 14:06:49.340 on Reigi {26}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003d34): trap number 11
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.Raise @ thread.cpp + 2704[19]
      NodeTools.RecoveryThread.DoTrap @ ntincrement.cpp + 4120[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4190[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 06A6D300
      patchArea : 0x0
      systhrd  : 06A790A0
        NodeBase.SysThread
        this : 06A790A0
        patchArea : 0x0
        nthread  : 00000094
        nid      : 3d34
        status   : 000
        event    : 0000038C
        guard    : 00000380
        priority : 1
        signal   : 0
      daemon   : 03551B78 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 035F55E0
        patchArea : 0x0
        stackBase  : 06A0F700
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035F55F8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2758752381813
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035F5618
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2758921892710
          limit    : 4
          count    : 3
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevTime  : 30096485
        currTime  : 0
        readyTime  : 2758976556943
        currStart  : 2758976562428
        currEnd    : 2758978362428
      test   : 0
      signal : 126
testcase end

    THR901 12-May-2020 14:06:49.341 on Reigi {27}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003d34)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillLocal completed.
nt>testcase begin recover.KillRemote
symbols set testcase.name recover.KillRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.12
nt>/ RECOVER kill remotely
nt>recover trap f SIGPURGE
nt>
    THR903 12-May-2020 14:06:51.264 on Reigi {28}
    by NodeBase.CliThread (tid=9, nid=0x00006730)
    for NodeTools.RecoveryThread (tid=15, nid=0x00002fb4)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 12-May-2020 14:06:51.268 on Reigi {29}
    in NodeTools.RecoveryThread (tid=15, nid=0x00002fb4): trap number 12
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1942[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3764[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 2047[0]
      NodeBase.Debug.ft @ debug.cpp + 72[9]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1881[11]
      NodeBase.Thread.Pause @ thread.cpp + 2588[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4199[26]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 06A6CDC0
      patchArea : 0x0
      systhrd  : 06A79070
        NodeBase.SysThread
        this : 06A79070
        patchArea : 0x0
        nthread  : 000004B8
        nid      : 2fb4
        status   : 000
        event    : 000004C8
        guard    : 0000046C
        priority : 1
        signal   : 0
      daemon   : 03551B78 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 035F4D58
        patchArea : 0x0
        stackBase  : 0915F968
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035F4D70
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2758976598067
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035F4D90
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2758995868747
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevTime  : 837
        currTime  : 0
        readyTime  : 2758976622421
        currStart  : 2758995831857
        currEnd    : 200000
      test   : 0
      signal : 0
testcase end

    THR901 12-May-2020 14:06:51.269 on Reigi {30}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00002fb4)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:52.426 on Reigi {31}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:52.464 on Reigi {32}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=58 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillRemote completed.
nt>testcase begin recover.InfiniteLoop
symbols set testcase.name recover.InfiniteLoop
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.13
nt>/ RECOVER infinite loop
nt>/ Enable use of SIGYIELD to kill thread that runs too long.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled f
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout t
nt>delay 1
nt>recover loop
nt>
    THR903 12-May-2020 14:06:54.637 on Reigi {33}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeTools.RecoveryThread (tid=15, nid=0x00002a90)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR902 12-May-2020 14:06:54.663 on Reigi {34}
    in NodeTools.RecoveryThread (tid=15, nid=0x00002a90): trap number 13
    type=Signal
    signal : 123 (SIGYIELD: Running Unpreemptably Too Long)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1942[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3764[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 2047[0]
      NodeBase.Debug.ft @ debug.cpp + 72[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 4218[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4159[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:06:56.884 on Reigi {35}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:06:56.912 on Reigi {36}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=131 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.InfiniteLoop completed.
nt>testcase begin recover.StackOverflow
symbols set testcase.name recover.StackOverflow
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.14
nt>/ ============== THE STACK OVERFLOW MAY TAKE TIME TO OCCUR ===============
nt>/ RECOVER stack overflow
nt>/ Enable breakpoints to provide time for overflow.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover stack
nt>
    THR902 12-May-2020 14:06:59.351 on Reigi {37}
    in NodeTools.RecoveryThread (tid=15, nid=0x00002a90): trap number 14
    type=Signal
    signal : 124 (SIGSTACK1: Stack Overflow: Attempt Recovery)
    errval : 0x1f43
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.StackCheck @ thread.cpp + 3280[16]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 2055[0]
      NodeBase.Debug.ft @ debug.cpp + 72[9]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4240[11]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      ...1997 functions omitted.
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4242[12]
delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:01.576 on Reigi {38}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:01.589 on Reigi {39}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=116 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.StackOverflow completed.
nt>testcase begin recover.MutexBlock
symbols set testcase.name recover.MutexBlock
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.19
nt>/ RECOVER block while holding mutex
nt>recover mutexblock
nt>
    SW900 12-May-2020 14:07:04.090 on Reigi {40}
    in Thread.EnterBlockingOperation
    errval=mutex holder  offset=0x1
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 105[22]
      NodeBase.Debug.SwLog @ debug.cpp + 217[25]
      NodeBase.Thread.EnterBlockingOperation @ thread.cpp + 1777[55]
      NodeBase.Thread.Pause @ thread.cpp + 2585[13]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4162[26]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexBlock completed.
nt>testcase begin recover.MutexExit
symbols set testcase.name recover.MutexExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.21
nt>/ RECOVER exit while holding mutex
nt>recover mutexexit
nt>
    THR907 12-May-2020 14:07:05.913 on Reigi {41}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00002a90)
    mutexes=1

    THR901 12-May-2020 14:07:05.913 on Reigi {42}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00002a90)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexExit completed.
nt>testcase begin recover.MutexTrap
symbols set testcase.name recover.MutexTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.22
nt>/ RECOVER trap while holding mutex
nt>recover mutextrap
nt>
    THR907 12-May-2020 14:07:07.844 on Reigi {43}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00006204)
    mutexes=1

    THR902 12-May-2020 14:07:07.844 on Reigi {44}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006204): trap number 15
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4171[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:08.959 on Reigi {45}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:08.993 on Reigi {46}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=55 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexTrap completed.
nt>testcase begin recover.TrapInRecover
symbols set testcase.name recover.TrapInRecover
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.15
nt>/ RECOVER trap during recovery
nt>swflags set &flag.recovertrap on
nt>delay 1
nt>recover swerr
nt>
    THR902 12-May-2020 14:07:10.736 on Reigi {47}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006204): trap number 16
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 205[65]
      NodeTools.RecoveryThread.DoSwerr @ ntincrement.cpp + 4098[22]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4184[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 12-May-2020 14:07:10.742 on Reigi {48}
    in NodeTools.RecoveryThread (tid=15, nid=0x00006204): trap number 17
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    TRAP DURING RECOVERY.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.Recover @ ntincrement.cpp + 4231[0]
      NodeBase.Thread.Start @ thread.cpp + 3337[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>swflags set &flag.recovertrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.TrapInRecover completed.
nt>testcase begin recover.ThreadCtorTrap
symbols set testcase.name recover.ThreadCtorTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.20
nt>/ RECOVER thread constructor trap
nt>/ InitThread will trap when it invokes RecoveryDaemon.CreateThread
nt>/ to recreate the recovery thread.
nt>recover ctortrap
nt>
    THR901 12-May-2020 14:07:14.077 on Reigi {49}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00006204)
    signal=0 (Normal Exit)

    THR900 12-May-2020 14:07:14.101 on Reigi {50}
    thread=NodeBase.Thread (tid=15, nid=0x000048fc)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 186[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1342[16]
      NLG_Return @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 77[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3955[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 135[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 427[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 308[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 257[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 06A6CEC0
      patchArea : 0x0
      systhrd  : 06A78DD0
        NodeBase.SysThread
        this : 06A78DD0
        patchArea : 0x0
        nthread  : 00000460
        nid      : 48fc
        status   : 000
        event    : 00000520
        guard    : 00000514
        priority : 1
        signal   : 0
      daemon   : 03551B78 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 035F5880
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 1
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035F5898
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759223962281
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035F58B8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759223962367
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevTime  : 0
        currTime  : 0
        readyTime  : 0
        currStart  : 0
        currEnd    : 0
testcase end

    SW900 12-May-2020 14:07:14.108 on Reigi {51}
    in Threads.GetState
    errval=orphan exited  offset=0x48fc
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 105[22]
      NodeBase.Debug.SwLog @ debug.cpp + 217[25]
      NodeBase.Threads.GetState @ thread.cpp + 853[42]
      NodeBase.Thread.EnterThread @ thread.cpp + 1822[8]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 12-May-2020 14:07:14.110 on Reigi {52}
    in NodeBase.InitThread (tid=2, nid=0x000046cc): trap number 18
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.RecoveryThread @ ntincrement.cpp + 3985[0]
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 77[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3955[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 135[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 427[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 308[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 257[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:15.211 on Reigi {53}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:15.286 on Reigi {54}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=75 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.ThreadCtorTrap completed.
nt>testcase begin recover.DaemonReenable
symbols set testcase.name recover.DaemonReenable
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.25
nt>/ RECOVER disable daemon; kill thread; enable daemon; thread recreated
nt>daemons set 9 off
nt>delay 1
nt>sched kill 15
nt>
    THR903 12-May-2020 14:07:17.505 on Reigi {55}
    by NodeBase.CliThread (tid=9, nid=0x00006730)
    for NodeTools.RecoveryThread (tid=15, nid=0x00003d10)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
delay 2

    THR902 12-May-2020 14:07:17.508 on Reigi {56}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003d10): trap number 19
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1942[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3764[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 2047[0]
      NodeBase.Debug.ft @ debug.cpp + 72[9]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1881[11]
      NodeBase.Thread.Pause @ thread.cpp + 2588[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4199[26]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 06A6D240
      patchArea : 0x0
      systhrd  : 06A78DD0
        NodeBase.SysThread
        this : 06A78DD0
        patchArea : 0x0
        nthread  : 00000514
        nid      : 3d10
        status   : 000
        event    : 00000574
        guard    : 00000460
        priority : 1
        signal   : 0
      daemon   : 03551B78 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 035F4E00
        patchArea : 0x0
        stackBase  : 06A0FC18
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035F4E18
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759224296679
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035F4E38
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759258265124
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevTime  : 709
        currTime  : 0
        readyTime  : 2759224320019
        currStart  : 2759258239311
        currEnd    : 200000
      test   : 0
      signal : 0

    THR901 12-May-2020 14:07:17.509 on Reigi {57}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003d10)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

  * THR300 12-May-2020 14:07:17.510 on Reigi {58}
    Alarm ON: DAEMON9 (Thread(s) unavailable: DAEMON9)
    daemon=recover target=1 actual=0
nt>daemons set 9 on
nt>
    THR300 12-May-2020 14:07:19.535 on Reigi {59}
    Alarm OFF: DAEMON9 (Thread(s) unavailable: DAEMON9)
    daemon=recover target=1 actual=1
delay 1
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:21.695 on Reigi {60}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:21.779 on Reigi {61}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=145 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DaemonReenable completed.
nt>testcase begin recover.DaemonRetrap
symbols set testcase.name recover.DaemonRetrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.26
nt>/ RECOVER daemon retraps trying to recreate thread; reenable to create thread
nt>swflags set &flag.threadctorretrap on
nt>delay 1
nt>recover ctortrap
nt>
    THR901 12-May-2020 14:07:24.231 on Reigi {62}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003838)
    signal=0 (Normal Exit)

    THR900 12-May-2020 14:07:24.240 on Reigi {63}
    thread=NodeBase.Thread (tid=15, nid=0x00005328)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 186[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1342[16]
      NLG_Return @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 77[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3955[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 135[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 427[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 308[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 257[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 06A6D4C0
      patchArea : 0x0
      systhrd  : 06A79070
        NodeBase.SysThread
        this : 06A79070
        patchArea : 0x0
        nthread  : 000005D4
        nid      : 5328
        status   : 000
        event    : 000005A8
        guard    : 000005D0
        priority : 1
        signal   : 0
      daemon   : 03551B78 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 035F55E0
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035F55F8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759325510552
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035F5618
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759325510851
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevTime  : 0
        currTime  : 0
        readyTime  : 0
        currStart  : 0
        currEnd    : 0
delay 1

    SW900 12-May-2020 14:07:24.244 on Reigi {64}
    in Threads.GetState
    errval=orphan exited  offset=0x5328
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 105[22]
      NodeBase.Debug.SwLog @ debug.cpp + 217[25]
      NodeBase.Threads.GetState @ thread.cpp + 853[42]
      NodeBase.Thread.EnterThread @ thread.cpp + 1822[8]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 12-May-2020 14:07:24.246 on Reigi {65}
    in NodeBase.InitThread (tid=2, nid=0x000046cc): trap number 20
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.RecoveryThread @ ntincrement.cpp + 3985[0]
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 77[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3955[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 135[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 427[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 308[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 257[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR900 12-May-2020 14:07:24.253 on Reigi {66}
    thread=NodeBase.Thread (tid=15, nid=0x00006dec)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 186[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1342[16]
      NLG_Return @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 77[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3955[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 135[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 427[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 308[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 234[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 06A6D4C0
      patchArea : 0x0
      systhrd  : 06A78DD0
        NodeBase.SysThread
        this : 06A78DD0
        patchArea : 0x0
        nthread  : 000005A8
        nid      : 6dec
        status   : 000
        event    : 000005D4
        guard    : 000005D0
        priority : 1
        signal   : 0
      daemon   : 03551B78 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 035F5880
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 1
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 035F5898
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759325653561
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 035F58B8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 2759325653612
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevTime  : 0
        currTime  : 0
        readyTime  : 0
        currStart  : 0
        currEnd    : 0

    SW900 12-May-2020 14:07:24.255 on Reigi {67}
    in Threads.GetState
    errval=orphan exited  offset=0x6dec
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 105[22]
      NodeBase.Debug.SwLog @ debug.cpp + 217[25]
      NodeBase.Threads.GetState @ thread.cpp + 853[42]
      NodeBase.Thread.EnterThread @ thread.cpp + 1822[8]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 12-May-2020 14:07:24.257 on Reigi {68}
    in NodeBase.InitThread (tid=2, nid=0x000046cc): trap number 21
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.RecoveryThread @ ntincrement.cpp + 3991[0]
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 77[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3955[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 135[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 427[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 308[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 234[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

  * THR300 12-May-2020 14:07:24.258 on Reigi {69}
    Alarm ON: DAEMON9 (Thread(s) unavailable: DAEMON9)
    daemon=recover target=1 actual=0
nt>daemons set 9 on
nt>
    THR300 12-May-2020 14:07:25.275 on Reigi {70}
    Alarm OFF: DAEMON9 (Thread(s) unavailable: DAEMON9)
    daemon=recover target=1 actual=1
delay 1
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:27.433 on Reigi {71}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:27.512 on Reigi {72}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=120 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DaemonRetrap completed.
nt>testcase begin recover.DeleteRemote
symbols set testcase.name recover.DeleteRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.16
nt>/ RECOVER destroy remotely
nt>/ After deleting the thread, give it time to wake up and exit.
nt>recover delete f
nt>delay 5

    SW900 12-May-2020 14:07:30.278 on Reigi {73}
    in Threads.GetState
    errval=orphan exited  offset=0x3d34
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 105[22]
      NodeBase.Debug.SwLog @ debug.cpp + 217[25]
      NodeBase.Threads.GetState @ thread.cpp + 853[42]
      NodeBase.Thread.RunningThread @ thread.cpp + 3042[12]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1883[7]
      NodeBase.Thread.Pause @ thread.cpp + 2588[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4199[26]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:35.337 on Reigi {74}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:35.418 on Reigi {75}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=144 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteRemote completed.
nt>testcase begin recover.DeleteLocal
symbols set testcase.name recover.DeleteLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.17
nt>/ RECOVER destroy this
nt>recover delete t
nt>
    SW900 12-May-2020 14:07:36.868 on Reigi {76}
    in Threads.GetState
    errval=orphan exited  offset=0x3de8
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 105[22]
      NodeBase.Debug.SwLog @ debug.cpp + 217[25]
      NodeBase.Threads.GetState @ thread.cpp + 853[42]
      NodeBase.Thread.RunningThread @ thread.cpp + 3042[12]
      NodeBase.Thread.Pause @ thread.cpp + 2573[7]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4199[26]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteLocal completed.
nt>testcase begin recover.Ctrl-C
symbols set testcase.name recover.Ctrl-C
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.18
nt>/ =============== PREPARE TO ENTER CTRL-C, POSSIBLY TWICE ================
nt>/ RECOVER infinite loop
nt>delay 1
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout f
nt>delay 1
nt>recover loop
nt>
    THR903 12-May-2020 14:07:41.035 on Reigi {77}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeTools.RecoveryThread (tid=15, nid=0x000041cc)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR903 12-May-2020 14:07:41.802 on Reigi {78}
    for NodeTools.RecoveryThread (tid=15, nid=0x000041cc)
    signal=2 (SIGINT: Terminal Interrupt)

    THR902 12-May-2020 14:07:41.809 on Reigi {79}
    in NodeTools.RecoveryThread (tid=15, nid=0x000041cc): trap number 22
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1942[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3764[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 2047[0]
      NodeBase.Debug.ft @ debug.cpp + 72[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 4218[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4159[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR905 12-May-2020 14:07:41.810 on Reigi {80}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000041cc) overrun=880 msecs
delay 1
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:43.937 on Reigi {81}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:44.054 on Reigi {82}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=138 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Ctrl-C completed.
nt>testcase begin recover.Retrap
symbols set testcase.name recover.Retrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.23
nt>/ RECOVER trap during trap recovery
nt>swflags set &flag.threadretrap on
nt>delay 1
nt>recover badptr
nt>
    THR902 12-May-2020 14:07:46.562 on Reigi {83}
    in NodeTools.RecoveryThread (tid=15, nid=0x000041cc): trap number 23
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4254[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4153[0]
      NodeBase.Thread.Start @ thread.cpp + 3375[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 12-May-2020 14:07:46.568 on Reigi {84}
    in NodeTools.RecoveryThread (tid=15, nid=0x000041cc): trap number 24
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 2100[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 147[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeBase.Thread.TrapHandler @ thread.cpp + 3854[0]
      NodeBase.Thread.Start @ thread.cpp + 3421[46]
      NodeBase.Thread.EnterThread @ thread.cpp + 1835[0]
      register_onexit_function @ <unknown file> (err=487)
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1

    THR906 12-May-2020 14:07:46.576 on Reigi {85}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000041cc)
    signal=11 (SIGSEGV: Invalid Memory Reference)
nt>swflags set &flag.threadretrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 12-May-2020 14:07:48.726 on Reigi {86}
    by NodeBase.InitThread (tid=2, nid=0x000046cc)
    for NodeBase.CliThread (tid=9, nid=0x00006730)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 12-May-2020 14:07:48.795 on Reigi {87}
    thread=NodeBase.CliThread (tid=9, nid=0x00006730) overrun=89 msecs
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Retrap completed.
nt>testcase query
  Current test session:
    Passed: 26
    Failed: 0
  Testcase database:
    unreported: 0  failed: 0  re-execute: 0  passed: 117
nt>